// <auto-generated />
using System;
using Aegis.Universe.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aegis.Universe.Infrastructure.Migrations
{
    [DbContext(typeof(UniverseDbContext))]
    partial class UniverseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aegis.Universe.Domain.Entities.Symbol", b =>
                {
                    b.Property<Guid>("SymbolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("symbol_id");

                    b.Property<string>("AssetClass")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("asset_class");

                    b.Property<Instant>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("ticker");

                    b.Property<Instant>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.HasKey("SymbolId");

                    b.HasIndex("Ticker")
                        .IsUnique();

                    b.ToTable("symbol", (string)null);
                });

            modelBuilder.Entity("Aegis.Universe.Domain.Entities.Watchlist", b =>
                {
                    b.Property<Guid>("WatchlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("watchlist_id");

                    b.Property<Instant>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<bool>("IsMutable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_mutable");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("normalized_name");

                    b.Property<Instant>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.Property<string>("WatchlistType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("watchlist_type");

                    b.HasKey("WatchlistId");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("watchlist", (string)null);
                });

            modelBuilder.Entity("Aegis.Universe.Domain.Entities.WatchlistItem", b =>
                {
                    b.Property<Guid>("WatchlistItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("watchlist_item_id");

                    b.Property<Instant>("AddedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_utc");

                    b.Property<Guid>("SymbolId")
                        .HasColumnType("uuid")
                        .HasColumnName("symbol_id");

                    b.Property<Guid>("WatchlistId")
                        .HasColumnType("uuid")
                        .HasColumnName("watchlist_id");

                    b.HasKey("WatchlistItemId");

                    b.HasIndex("SymbolId");

                    b.HasIndex("WatchlistId", "SymbolId")
                        .IsUnique();

                    b.ToTable("watchlist_item", (string)null);
                });

            modelBuilder.Entity("Aegis.Universe.Domain.Entities.WatchlistItem", b =>
                {
                    b.HasOne("Aegis.Universe.Domain.Entities.Symbol", "Symbol")
                        .WithMany("WatchlistItems")
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aegis.Universe.Domain.Entities.Watchlist", "Watchlist")
                        .WithMany("WatchlistItems")
                        .HasForeignKey("WatchlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Symbol");

                    b.Navigation("Watchlist");
                });

            modelBuilder.Entity("Aegis.Universe.Domain.Entities.Symbol", b =>
                {
                    b.Navigation("WatchlistItems");
                });

            modelBuilder.Entity("Aegis.Universe.Domain.Entities.Watchlist", b =>
                {
                    b.Navigation("WatchlistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
