// <auto-generated />
using System;
using Aegis.MarketData.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aegis.MarketData.Infrastructure.Migrations
{
    [DbContext(typeof(MarketDataDbContext))]
    [Migration("20260312174240_ConvertMarketDataToNodaTime")]
    partial class ConvertMarketDataToNodaTime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aegis.MarketData.Domain.Entities.MarketDataBar", b =>
                {
                    b.Property<Guid>("BarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("bar_id");

                    b.Property<Instant>("BarTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bar_time_utc");

                    b.Property<decimal>("Close")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("close");

                    b.Property<Instant>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<decimal>("High")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("high");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("interval");

                    b.Property<bool>("IsReconciled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_reconciled");

                    b.Property<decimal>("Low")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("low");

                    b.Property<LocalDate>("MarketDate")
                        .HasColumnType("date")
                        .HasColumnName("market_date");

                    b.Property<decimal>("Open")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("open");

                    b.Property<string>("ProviderFeed")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider_feed");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider_name");

                    b.Property<string>("RuntimeState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("runtime_state");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("session_type");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("symbol");

                    b.Property<Instant>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.HasKey("BarId");

                    b.HasIndex("Symbol", "Interval");

                    b.HasIndex("Symbol", "Interval", "BarTimeUtc")
                        .IsUnique();

                    b.ToTable("bar", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
